### ISSUE TITLE
LiDAR simulation has "gaps"

### ISSUE THREAD

**Issue by fotisk07** [fotisk07/SI-Project#6]

**Comment by CeType** [comment]
Can you elaborate ?

**Comment by fotisk07** [comment]
[Log4 (1).txt](https://github.com/fotisk07/SI-Project/files/3774944/Log4.1.txt)

At coordinates (1,4), (1,5), (1,6) for example, the value of the created map is zero when it should be something negative

**Comment by CeType** [comment]
I see

**Comment by CeType** [comment]
The issue was here:
https://github.com/fotisk07/SI-Project/blob/aa50a13e49ec95a23d46a6eb016697d37470f9f2/Mapping/Map.py#L28

Should have been an `or` statement

This makes the log change correctly:
[BeforeLog](https://github.com/fotisk07/SI-Project/files/3774997/Log4.txt)
[AfterLog](https://github.com/fotisk07/SI-Project/files/3774999/Log7.txt)

**Comment by fotisk07** [comment]
Great thanks
